### ISSUE TITLE
[Build] archive/tar: write too long error

### ISSUE THREAD

**Issue by compleatang** [monax/compass#9]
When we want to build docker with `go build -mod vendor` then we need to give the docker build context the files properly. We currently have a relatively naive implementation of go's tar library which in CI causes problems from symlinks. This appears to be correctable but will take some work.... See, e.g., this IPFS issue -> https://github.com/ipfs/go-ipfs/issues/4667

**Comment by gregdhill** [comment]
Fixed in https://github.com/monax/compass/commit/9838c87772faa572b81e7705a083286edbfd66c9
